CREATE TABLE IF NOT EXISTS wfm_schema.tx_field_operation_non_alarm (
    tx_field_operation_non_alarm_id BIGINT PRIMARY KEY UNIQUE,
    ticket_no VARCHAR(25),
    site_id VARCHAR(10),
    cluster_area VARCHAR(255),
    category VARCHAR(25),
    ticket_subject VARCHAR(50),
    job_details VARCHAR(255),
    job_targets VARCHAR(255),
    sla_start TIMESTAMP WITHOUT TIME ZONE,
    sla_end TIMESTAMP WITHOUT TIME ZONE,
    sla_range VARCHAR(25),
    created_by BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    modified_by BIGINT,
    modified_at TIMESTAMP WITHOUT TIME ZONE,
    activity_name VARCHAR(255),
    role_name VARCHAR(255),
    respone_time TIMESTAMP WITHOUT TIME ZONE,
    submit_time TIMESTAMP WITHOUT TIME ZONE,
    user_submitter VARCHAR(255),
    approve_time TIMESTAMP WITHOUT TIME ZONE,
    user_approve VARCHAR(255),
    note VARCHAR(255),
    review VARCHAR(255),
    status VARCHAR(25),
    rootcause1 VARCHAR(255),
    rootcause2 VARCHAR(255),
    rootcause3 VARCHAR(255),
    rootcause_remark VARCHAR(255),
    resolution_action VARCHAR(255),
    pic_id VARCHAR(10),
    pic_name VARCHAR(255),
    description VARCHAR(255),
    "name" VARCHAR(255),
    issue_category VARCHAR(255),
    is_asset_change bool,
    take_over_at TIMESTAMP WITHOUT TIME ZONE,
    checkin_at TIMESTAMP WITHOUT TIME ZONE,
    follow_up_at TIMESTAMP WITHOUT TIME ZONE,
    request_permit_at TIMESTAMP WITHOUT TIME ZONE,
    is_exclude bool DEFAULT false
);