CREATE TABLE IF NOT EXISTS wfm_schema.tx_inap (
    ticket_number_inap VARCHAR(25),
    ticket_number_swfm VARCHAR(25),
    severity VARCHAR(25),
    type_ticket VARCHAR(25),
    site_id VARCHAR(10),
    site_name VARCHAR(200),
    site_class VARCHAR(50),
    cluster_to VARCHAR(100),
    sub_cluster VARCHAR(50),
    impact VARCHAR(25),
    occured_time TIMESTAMP,
    created_at TIMESTAMP,
    duration_ticket INTERVAL,
    ne_class VARCHAR(25),
    ticket_inap_status VARCHAR(25),
    ticket_swmf_status VARCHAR(25),
    pic_take_over_ticket VARCHAR(100),
    nop VARCHAR(50),
    regional VARCHAR(50),
    area VARCHAR(10),
    is_escalate BOOLEAN,
    escalate_to VARCHAR(50),
    cleared_time TIMESTAMP,
    is_auto_resolved BOOLEAN,
    rh_start,
    rh_start_time,
    rh_stop,
    rh_stop_time,
    rc_owner VARCHAR(100),
    rc_category,
    rc_1,
    rc_2,
    note TEXT,
    resolution_action TEXT,
    take_over_date TIMESTAMP,
    check_in_at TIMESTAMP,
    inap_rc_1,
    inap_rc_2,
    inap_resolution_action TEXT,
    sla_status BOOLEAN,
    fault_level VARCHAR(50),
    nossa_no VARCHAR(50),
    assignee_group VARCHAR(255),
    summary TEXT,
    description TEXT,
    submitted_time TIMESTAMP,
    incident_priority NUMERIC(8, 2),
    hub VARCHAR(10),
    is_exclude_in_kpi BOOLEAN,
    ticket_creation TIMESTAMP,
    ticket_creator VARCHAR(50),
    site_cleared_on TIMESTAMP,
    rank INT,
    closed_at TIMESTAMP,
    dispatch_by VARCHAR(200),
    dispatch_date TIMESTAMP
)