select * from wfm_uso_schema.tm_parameter tp 
where tp."group" = 'StatusTag'

INSERT INTO wfm_uso_schema.tm_parameter ("group", value1, value2)
VALUES
  ('StatusTag', 'NEW', 'Indigo'),
  ('StatusTag', 'UPGRADE DOWNGRADE DAYA', 'Indigo'),
  ('StatusTag', 'WAITING VERIFY CLAIM INFO', 'Indigo'),
  ('StatusTag', 'WAITING FOR TPAS', 'Violet'),
  ('StatusTag', 'WAITING INVESTIGATION BY FMC', 'Violet'),
  ('StatusTag', 'WAITING ACKNOWLEDGE NOP', 'Violet'),
  ('StatusTag', 'WAITING REVIEW KWH RECORD', 'Violet'),
  ('StatusTag', 'WAITING SUBMIT PLN REPORT', 'Violet'),
  ('StatusTag', 'REVISED', 'Violet'),
  ('StatusTag', 'WAITING REVIEW CTO MANAGER', 'Violet'),
  ('StatusTag', 'ASSIGNED', 'Grape'),
  ('StatusTag', 'WAITING NOP MGR APPROVAL', 'Grape'),
  ('StatusTag', 'WAITING NOS MGR APPROVAL', 'Grape'),
  ('StatusTag', 'IN PROGRESS', 'Pink'),
  ('StatusTag', 'WAITING BAIV NOP', 'Pink'),
  ('StatusTag', 'WAITING DAISY SPPH NOS', 'Pink'),
  ('StatusTag', 'WAITING REVIEW SPV TO', 'Pink'),
  ('StatusTag', 'WAITING PRICE NEGOTIATION FMC', 'Teal'),
  ('StatusTag', 'UNDER REVIEW BOQ NOS', 'Teal'),
  ('StatusTag', 'WAITING FOLLOW UP TO PLN', 'Teal'),
  ('StatusTag', 'WAITING ACKNOWLEDGE NOS', 'Teal'),
  ('StatusTag', 'WAITING PLN REPORT REVIEW', 'Teal'),
  ('StatusTag', 'WAITING REVIEW NISM MANAGER', 'Teal'),
  ('StatusTag', 'RESOLVED', 'Violet'),
  ('StatusTag', 'SUBMITTED', 'Violet'),
  ('StatusTag', 'COMPLETED', 'Violet'),
  ('StatusTag', 'DEACTIVE', 'Violet'),
  ('StatusTag', 'WAITING ACTIVITY REVIEW', 'Violet'),
  ('StatusTag', 'FULL CUT OFF', 'Violet'),
  ('StatusTag', 'DISMANTLE', 'Violet'),
  ('StatusTag', 'COMPLETED SPE RELEASED', 'Violet'),
  ('StatusTag', 'OPEN', 'Red'),
  ('StatusTag', 'CLOSED', 'Red'),
  ('StatusTag', 'REJECTED', 'Grape'),
  ('StatusTag', 'TAKE OUT', 'Grape'),
  ('StatusTag', 'REVISED KWH RECORD', 'Grape'),
  ('StatusTag', 'REVISED PLN REPORT', 'Grape'),
  ('StatusTag', 'WAITING REVISED', 'Grape'),
  ('StatusTag', 'APPROVED', 'Green'),
  ('StatusTag', 'ACTIVE', 'Green'),
  ('StatusTag', 'ACTIVATION', 'Green'),
  ('StatusTag', 'ON SERVICE', 'Green'),
  ('StatusTag', 'CLOSE', 'Green'),
  ('StatusTag', 'ASSIGN', 'Yellow'),
  ('StatusTag', 'INVESTIGATE', 'Orange'),
  ('StatusTag', 'RESOLVE', 'Lime'),
  ('StatusTag', 'CANCEL', 'Red'),
  ('StatusTag', 'PARTIAL CUT OFF', 'Blue'),
  ('StatusTag', 'WAITING INVESTIGATION BY ENOM', 'Blue'),
  ('StatusTag', 'REVIEW ESCALATE NOS', 'Blue'),
  ('StatusTag', 'TAKEOUT', 'Pink'),
  ('StatusTag', 'CANCELED', 'Pink'),
  ('StatusTag', 'WAITING CLAIM INFORMATION', 'Yellow'),
  ('StatusTag', 'WAITING CLAIM INFORMATION', 'Lime');