USE [outsystems_log]

SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Cyclic_Job_0]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Cyclic_Job_1]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Cyclic_Job_2]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Cyclic_Job_3]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Cyclic_Job_4]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Cyclic_Job_5]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Cyclic_Job_6]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Cyclic_Job_7]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Cyclic_Job_8]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Cyclic_Job_9]
GO
TRUNCATE TABLE [dbo].[oslog_Cyclic_Job_0]
TRUNCATE TABLE [dbo].[oslog_Cyclic_Job_1]
TRUNCATE TABLE [dbo].[oslog_Cyclic_Job_2]
TRUNCATE TABLE [dbo].[oslog_Cyclic_Job_3]
TRUNCATE TABLE [dbo].[oslog_Cyclic_Job_4]
TRUNCATE TABLE [dbo].[oslog_Cyclic_Job_5]
TRUNCATE TABLE [dbo].[oslog_Cyclic_Job_6]
TRUNCATE TABLE [dbo].[oslog_Cyclic_Job_7]
TRUNCATE TABLE [dbo].[oslog_Cyclic_Job_8]
TRUNCATE TABLE [dbo].[oslog_Cyclic_Job_9]
GO

SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Error_0]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Error_1]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Error_2]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Error_3]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Error_4]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Error_5]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Error_6]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Error_7]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Error_8]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Error_9]
GO
TRUNCATE TABLE [dbo].[oslog_Error_0]
TRUNCATE TABLE [dbo].[oslog_Error_1]
TRUNCATE TABLE [dbo].[oslog_Error_2]
TRUNCATE TABLE [dbo].[oslog_Error_3]
TRUNCATE TABLE [dbo].[oslog_Error_4]
TRUNCATE TABLE [dbo].[oslog_Error_5]
TRUNCATE TABLE [dbo].[oslog_Error_6]
TRUNCATE TABLE [dbo].[oslog_Error_7]
TRUNCATE TABLE [dbo].[oslog_Error_8]
TRUNCATE TABLE [dbo].[oslog_Error_9]
GO

SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Error_Detail_0]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Error_Detail_1]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Error_Detail_2]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Error_Detail_3]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Error_Detail_4]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Error_Detail_5]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Error_Detail_6]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Error_Detail_7]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Error_Detail_8]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Error_Detail_9]
GO
TRUNCATE TABLE [dbo].[oslog_Error_Detail_0]
TRUNCATE TABLE [dbo].[oslog_Error_Detail_1]
TRUNCATE TABLE [dbo].[oslog_Error_Detail_2]
TRUNCATE TABLE [dbo].[oslog_Error_Detail_3]
TRUNCATE TABLE [dbo].[oslog_Error_Detail_4]
TRUNCATE TABLE [dbo].[oslog_Error_Detail_5]
TRUNCATE TABLE [dbo].[oslog_Error_Detail_6]
TRUNCATE TABLE [dbo].[oslog_Error_Detail_7]
TRUNCATE TABLE [dbo].[oslog_Error_Detail_8]
TRUNCATE TABLE [dbo].[oslog_Error_Detail_9]
GO

SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Extension_0]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Extension_1]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Extension_2]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Extension_3]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Extension_4]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Extension_5]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Extension_6]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Extension_7]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Extension_8]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Extension_9]
GO
TRUNCATE TABLE [dbo].[oslog_Extension_0]
TRUNCATE TABLE [dbo].[oslog_Extension_1]
TRUNCATE TABLE [dbo].[oslog_Extension_2]
TRUNCATE TABLE [dbo].[oslog_Extension_3]
TRUNCATE TABLE [dbo].[oslog_Extension_4]
TRUNCATE TABLE [dbo].[oslog_Extension_5]
TRUNCATE TABLE [dbo].[oslog_Extension_6]
TRUNCATE TABLE [dbo].[oslog_Extension_7]
TRUNCATE TABLE [dbo].[oslog_Extension_8]
TRUNCATE TABLE [dbo].[oslog_Extension_9]
GO

SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_General_0]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_General_1]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_General_2]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_General_3]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_General_4]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_General_5]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_General_6]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_General_7]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_General_8]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_General_9]
GO
TRUNCATE TABLE [dbo].[oslog_General_0]
TRUNCATE TABLE [dbo].[oslog_General_1]
TRUNCATE TABLE [dbo].[oslog_General_2]
TRUNCATE TABLE [dbo].[oslog_General_3]
TRUNCATE TABLE [dbo].[oslog_General_4]
TRUNCATE TABLE [dbo].[oslog_General_5]
TRUNCATE TABLE [dbo].[oslog_General_6]
TRUNCATE TABLE [dbo].[oslog_General_7]
TRUNCATE TABLE [dbo].[oslog_General_8]
TRUNCATE TABLE [dbo].[oslog_General_9]
GO

SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Integration_0]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Integration_1]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Integration_2]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Integration_3]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Integration_4]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Integration_5]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Integration_6]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Integration_7]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Integration_8]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Integration_9]
GO
TRUNCATE TABLE [dbo].[oslog_Integration_0]
TRUNCATE TABLE [dbo].[oslog_Integration_1]
TRUNCATE TABLE [dbo].[oslog_Integration_2]
TRUNCATE TABLE [dbo].[oslog_Integration_3]
TRUNCATE TABLE [dbo].[oslog_Integration_4]
TRUNCATE TABLE [dbo].[oslog_Integration_5]
TRUNCATE TABLE [dbo].[oslog_Integration_6]
TRUNCATE TABLE [dbo].[oslog_Integration_7]
TRUNCATE TABLE [dbo].[oslog_Integration_8]
TRUNCATE TABLE [dbo].[oslog_Integration_9]
GO

SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_mobile_request_0]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_mobile_request_1]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_mobile_request_2]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_mobile_request_3]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_mobile_request_4]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_mobile_request_5]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_mobile_request_6]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_mobile_request_7]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_mobile_request_8]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_mobile_request_9]
GO
TRUNCATE TABLE [dbo].[oslog_mobile_request_0]
TRUNCATE TABLE [dbo].[oslog_mobile_request_1]
TRUNCATE TABLE [dbo].[oslog_mobile_request_2]
TRUNCATE TABLE [dbo].[oslog_mobile_request_3]
TRUNCATE TABLE [dbo].[oslog_mobile_request_4]
TRUNCATE TABLE [dbo].[oslog_mobile_request_5]
TRUNCATE TABLE [dbo].[oslog_mobile_request_6]
TRUNCATE TABLE [dbo].[oslog_mobile_request_7]
TRUNCATE TABLE [dbo].[oslog_mobile_request_8]
TRUNCATE TABLE [dbo].[oslog_mobile_request_9]
GO

SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_MR_Detail_0]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_MR_Detail_1]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_MR_Detail_2]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_MR_Detail_3]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_MR_Detail_4]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_MR_Detail_5]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_MR_Detail_6]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_MR_Detail_7]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_MR_Detail_8]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_MR_Detail_9]
GO
TRUNCATE TABLE [dbo].[oslog_MR_Detail_0]
TRUNCATE TABLE [dbo].[oslog_MR_Detail_1]
TRUNCATE TABLE [dbo].[oslog_MR_Detail_2]
TRUNCATE TABLE [dbo].[oslog_MR_Detail_3]
TRUNCATE TABLE [dbo].[oslog_MR_Detail_4]
TRUNCATE TABLE [dbo].[oslog_MR_Detail_5]
TRUNCATE TABLE [dbo].[oslog_MR_Detail_6]
TRUNCATE TABLE [dbo].[oslog_MR_Detail_7]
TRUNCATE TABLE [dbo].[oslog_MR_Detail_8]
TRUNCATE TABLE [dbo].[oslog_MR_Detail_9]
GO

SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Screen_0]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Screen_1]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Screen_2]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Screen_3]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Screen_4]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Screen_5]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Screen_6]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Screen_7]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Screen_8]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Screen_9]
GO
TRUNCATE TABLE [dbo].[oslog_Screen_0]
TRUNCATE TABLE [dbo].[oslog_Screen_1]
TRUNCATE TABLE [dbo].[oslog_Screen_2]
TRUNCATE TABLE [dbo].[oslog_Screen_3]
TRUNCATE TABLE [dbo].[oslog_Screen_4]
TRUNCATE TABLE [dbo].[oslog_Screen_5]
TRUNCATE TABLE [dbo].[oslog_Screen_6]
TRUNCATE TABLE [dbo].[oslog_Screen_7]
TRUNCATE TABLE [dbo].[oslog_Screen_8]
TRUNCATE TABLE [dbo].[oslog_Screen_9]
GO

SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Int_Detail_0]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Int_Detail_1]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Int_Detail_2]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Int_Detail_3]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Int_Detail_4]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Int_Detail_5]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Int_Detail_6]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Int_Detail_7]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Int_Detail_8]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Int_Detail_9]
GO
TRUNCATE TABLE [dbo].[oslog_Int_Detail_0]
TRUNCATE TABLE [dbo].[oslog_Int_Detail_1]
TRUNCATE TABLE [dbo].[oslog_Int_Detail_2]
TRUNCATE TABLE [dbo].[oslog_Int_Detail_3]
TRUNCATE TABLE [dbo].[oslog_Int_Detail_4]
TRUNCATE TABLE [dbo].[oslog_Int_Detail_5]
TRUNCATE TABLE [dbo].[oslog_Int_Detail_6]
TRUNCATE TABLE [dbo].[oslog_Int_Detail_7]
TRUNCATE TABLE [dbo].[oslog_Int_Detail_8]
TRUNCATE TABLE [dbo].[oslog_Int_Detail_9]
GO

SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Web_Service_0]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Web_Service_1]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Web_Service_2]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Web_Service_3]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Web_Service_4]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Web_Service_5]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Web_Service_6]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Web_Service_7]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Web_Service_8]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_Web_Service_9]
GO
TRUNCATE TABLE [dbo].[oslog_Web_Service_0]
TRUNCATE TABLE [dbo].[oslog_Web_Service_1]
TRUNCATE TABLE [dbo].[oslog_Web_Service_2]
TRUNCATE TABLE [dbo].[oslog_Web_Service_3]
TRUNCATE TABLE [dbo].[oslog_Web_Service_4]
TRUNCATE TABLE [dbo].[oslog_Web_Service_5]
TRUNCATE TABLE [dbo].[oslog_Web_Service_6]
TRUNCATE TABLE [dbo].[oslog_Web_Service_7]
TRUNCATE TABLE [dbo].[oslog_Web_Service_8]
TRUNCATE TABLE [dbo].[oslog_Web_Service_9]
GO

SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_SrvAPI_Detail_0]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_SrvAPI_Detail_1]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_SrvAPI_Detail_2]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_SrvAPI_Detail_3]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_SrvAPI_Detail_4]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_SrvAPI_Detail_5]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_SrvAPI_Detail_6]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_SrvAPI_Detail_7]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_SrvAPI_Detail_8]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_SrvAPI_Detail_9]
GO
TRUNCATE TABLE [outsystems_log].[dbo].[oslog_SrvAPI_Detail_0]
TRUNCATE TABLE [outsystems_log].[dbo].[oslog_SrvAPI_Detail_1]
TRUNCATE TABLE [outsystems_log].[dbo].[oslog_SrvAPI_Detail_2]
TRUNCATE TABLE [outsystems_log].[dbo].[oslog_SrvAPI_Detail_3]
TRUNCATE TABLE [outsystems_log].[dbo].[oslog_SrvAPI_Detail_4]
TRUNCATE TABLE [outsystems_log].[dbo].[oslog_SrvAPI_Detail_5]
TRUNCATE TABLE [outsystems_log].[dbo].[oslog_SrvAPI_Detail_6]
TRUNCATE TABLE [outsystems_log].[dbo].[oslog_SrvAPI_Detail_7]
TRUNCATE TABLE [outsystems_log].[dbo].[oslog_SrvAPI_Detail_8]
TRUNCATE TABLE [outsystems_log].[dbo].[oslog_SrvAPI_Detail_9]
GO

SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_SrvAPI_0]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_SrvAPI_1]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_SrvAPI_2]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_SrvAPI_3]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_SrvAPI_4]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_SrvAPI_5]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_SrvAPI_6]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_SrvAPI_7]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_SrvAPI_8]
SELECT TOP 100 * FROM [outsystems_log].[dbo].[oslog_SrvAPI_9]
GO
TRUNCATE TABLE [outsystems_log].[dbo].[oslog_SrvAPI_0]
TRUNCATE TABLE [outsystems_log].[dbo].[oslog_SrvAPI_1]
TRUNCATE TABLE [outsystems_log].[dbo].[oslog_SrvAPI_2]
TRUNCATE TABLE [outsystems_log].[dbo].[oslog_SrvAPI_3]
TRUNCATE TABLE [outsystems_log].[dbo].[oslog_SrvAPI_4]
TRUNCATE TABLE [outsystems_log].[dbo].[oslog_SrvAPI_5]
TRUNCATE TABLE [outsystems_log].[dbo].[oslog_SrvAPI_6]
TRUNCATE TABLE [outsystems_log].[dbo].[oslog_SrvAPI_7]
TRUNCATE TABLE [outsystems_log].[dbo].[oslog_SrvAPI_8]
TRUNCATE TABLE [outsystems_log].[dbo].[oslog_SrvAPI_9]
GO
